### ISSUE TITLE
Unable to find resource 'org.testdriven:testdriven:pom:2'

### ISSUE THREAD

**Issue by sriharigovindharaj** [testdriven/spring-groovy-web-archetype#1]
I am getting a fatal error when I executed 'mvn install' after pulling the archetype source from GitHub.

[INFO] Unable to find resource 'org.testdriven:testdriven:pom:2' in repository central (http://repo1.maven.org/maven2)
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

If this resource is not found in the repo1.maven.org, what other public repositories might have it?

**Comment by padcom** [comment]
It should already work properly. Reopen if this is still an issue
